vlog -work work C:/Users/jfotoya.JAVERIANA/Desktop/Single_Cycle_Mips_VHDL/simulation/modelsim/RFWaveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.RF_vlg_vec_tst
onerror {resume}
add wave {RF_vlg_vec_tst/i1/rd}
add wave {RF_vlg_vec_tst/i1/rd[4]}
add wave {RF_vlg_vec_tst/i1/rd[3]}
add wave {RF_vlg_vec_tst/i1/rd[2]}
add wave {RF_vlg_vec_tst/i1/rd[1]}
add wave {RF_vlg_vec_tst/i1/rd[0]}
add wave {RF_vlg_vec_tst/i1/readData1}
add wave {RF_vlg_vec_tst/i1/readData1[31]}
add wave {RF_vlg_vec_tst/i1/readData1[30]}
add wave {RF_vlg_vec_tst/i1/readData1[29]}
add wave {RF_vlg_vec_tst/i1/readData1[28]}
add wave {RF_vlg_vec_tst/i1/readData1[27]}
add wave {RF_vlg_vec_tst/i1/readData1[26]}
add wave {RF_vlg_vec_tst/i1/readData1[25]}
add wave {RF_vlg_vec_tst/i1/readData1[24]}
add wave {RF_vlg_vec_tst/i1/readData1[23]}
add wave {RF_vlg_vec_tst/i1/readData1[22]}
add wave {RF_vlg_vec_tst/i1/readData1[21]}
add wave {RF_vlg_vec_tst/i1/readData1[20]}
add wave {RF_vlg_vec_tst/i1/readData1[19]}
add wave {RF_vlg_vec_tst/i1/readData1[18]}
add wave {RF_vlg_vec_tst/i1/readData1[17]}
add wave {RF_vlg_vec_tst/i1/readData1[16]}
add wave {RF_vlg_vec_tst/i1/readData1[15]}
add wave {RF_vlg_vec_tst/i1/readData1[14]}
add wave {RF_vlg_vec_tst/i1/readData1[13]}
add wave {RF_vlg_vec_tst/i1/readData1[12]}
add wave {RF_vlg_vec_tst/i1/readData1[11]}
add wave {RF_vlg_vec_tst/i1/readData1[10]}
add wave {RF_vlg_vec_tst/i1/readData1[9]}
add wave {RF_vlg_vec_tst/i1/readData1[8]}
add wave {RF_vlg_vec_tst/i1/readData1[7]}
add wave {RF_vlg_vec_tst/i1/readData1[6]}
add wave {RF_vlg_vec_tst/i1/readData1[5]}
add wave {RF_vlg_vec_tst/i1/readData1[4]}
add wave {RF_vlg_vec_tst/i1/readData1[3]}
add wave {RF_vlg_vec_tst/i1/readData1[2]}
add wave {RF_vlg_vec_tst/i1/readData1[1]}
add wave {RF_vlg_vec_tst/i1/readData1[0]}
add wave {RF_vlg_vec_tst/i1/readData2}
add wave {RF_vlg_vec_tst/i1/readData2[31]}
add wave {RF_vlg_vec_tst/i1/readData2[30]}
add wave {RF_vlg_vec_tst/i1/readData2[29]}
add wave {RF_vlg_vec_tst/i1/readData2[28]}
add wave {RF_vlg_vec_tst/i1/readData2[27]}
add wave {RF_vlg_vec_tst/i1/readData2[26]}
add wave {RF_vlg_vec_tst/i1/readData2[25]}
add wave {RF_vlg_vec_tst/i1/readData2[24]}
add wave {RF_vlg_vec_tst/i1/readData2[23]}
add wave {RF_vlg_vec_tst/i1/readData2[22]}
add wave {RF_vlg_vec_tst/i1/readData2[21]}
add wave {RF_vlg_vec_tst/i1/readData2[20]}
add wave {RF_vlg_vec_tst/i1/readData2[19]}
add wave {RF_vlg_vec_tst/i1/readData2[18]}
add wave {RF_vlg_vec_tst/i1/readData2[17]}
add wave {RF_vlg_vec_tst/i1/readData2[16]}
add wave {RF_vlg_vec_tst/i1/readData2[15]}
add wave {RF_vlg_vec_tst/i1/readData2[14]}
add wave {RF_vlg_vec_tst/i1/readData2[13]}
add wave {RF_vlg_vec_tst/i1/readData2[12]}
add wave {RF_vlg_vec_tst/i1/readData2[11]}
add wave {RF_vlg_vec_tst/i1/readData2[10]}
add wave {RF_vlg_vec_tst/i1/readData2[9]}
add wave {RF_vlg_vec_tst/i1/readData2[8]}
add wave {RF_vlg_vec_tst/i1/readData2[7]}
add wave {RF_vlg_vec_tst/i1/readData2[6]}
add wave {RF_vlg_vec_tst/i1/readData2[5]}
add wave {RF_vlg_vec_tst/i1/readData2[4]}
add wave {RF_vlg_vec_tst/i1/readData2[3]}
add wave {RF_vlg_vec_tst/i1/readData2[2]}
add wave {RF_vlg_vec_tst/i1/readData2[1]}
add wave {RF_vlg_vec_tst/i1/readData2[0]}
add wave {RF_vlg_vec_tst/i1/rs}
add wave {RF_vlg_vec_tst/i1/rs[4]}
add wave {RF_vlg_vec_tst/i1/rs[3]}
add wave {RF_vlg_vec_tst/i1/rs[2]}
add wave {RF_vlg_vec_tst/i1/rs[1]}
add wave {RF_vlg_vec_tst/i1/rs[0]}
add wave {RF_vlg_vec_tst/i1/rt}
add wave {RF_vlg_vec_tst/i1/rt[4]}
add wave {RF_vlg_vec_tst/i1/rt[3]}
add wave {RF_vlg_vec_tst/i1/rt[2]}
add wave {RF_vlg_vec_tst/i1/rt[1]}
add wave {RF_vlg_vec_tst/i1/rt[0]}
add wave {RF_vlg_vec_tst/i1/rw}
add wave {RF_vlg_vec_tst/i1/writeData}
add wave {RF_vlg_vec_tst/i1/writeData[31]}
add wave {RF_vlg_vec_tst/i1/writeData[30]}
add wave {RF_vlg_vec_tst/i1/writeData[29]}
add wave {RF_vlg_vec_tst/i1/writeData[28]}
add wave {RF_vlg_vec_tst/i1/writeData[27]}
add wave {RF_vlg_vec_tst/i1/writeData[26]}
add wave {RF_vlg_vec_tst/i1/writeData[25]}
add wave {RF_vlg_vec_tst/i1/writeData[24]}
add wave {RF_vlg_vec_tst/i1/writeData[23]}
add wave {RF_vlg_vec_tst/i1/writeData[22]}
add wave {RF_vlg_vec_tst/i1/writeData[21]}
add wave {RF_vlg_vec_tst/i1/writeData[20]}
add wave {RF_vlg_vec_tst/i1/writeData[19]}
add wave {RF_vlg_vec_tst/i1/writeData[18]}
add wave {RF_vlg_vec_tst/i1/writeData[17]}
add wave {RF_vlg_vec_tst/i1/writeData[16]}
add wave {RF_vlg_vec_tst/i1/writeData[15]}
add wave {RF_vlg_vec_tst/i1/writeData[14]}
add wave {RF_vlg_vec_tst/i1/writeData[13]}
add wave {RF_vlg_vec_tst/i1/writeData[12]}
add wave {RF_vlg_vec_tst/i1/writeData[11]}
add wave {RF_vlg_vec_tst/i1/writeData[10]}
add wave {RF_vlg_vec_tst/i1/writeData[9]}
add wave {RF_vlg_vec_tst/i1/writeData[8]}
add wave {RF_vlg_vec_tst/i1/writeData[7]}
add wave {RF_vlg_vec_tst/i1/writeData[6]}
add wave {RF_vlg_vec_tst/i1/writeData[5]}
add wave {RF_vlg_vec_tst/i1/writeData[4]}
add wave {RF_vlg_vec_tst/i1/writeData[3]}
add wave {RF_vlg_vec_tst/i1/writeData[2]}
add wave {RF_vlg_vec_tst/i1/writeData[1]}
add wave {RF_vlg_vec_tst/i1/writeData[0]}
run -all
